version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
      #user: uid:gid
    network_mode: 'host'
    volumes:
      - /config:/config
      - /cache:/cache
      - /media/bigdata/BigBittorentDownloads/movies:/media/movies
      - /media/bigdata/BigBittorentDownloads/series:/media/series
        #- /path/to/media2:/media2:ro
    restart: 'unless-stopped'
      # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.local
      #               # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
